name = "TrustRegionBayesianOptimization"
uuid = "b798f86f-5fa2-4fcd-a5c1-3fd0da84cdd0"
authors = ["Samuel Belko <samuelbelko@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
